package pt.ulisboa.tecnico.socialsoftware.humanaethica.exceptions;

public enum ErrorMessage {
    INVALID_TYPE_FOR_AUTH_USER("Invalid type for auth user"),
    INVALID_AUTH_USERNAME("Username: %s, belongs to a different authentication method"),
    INVALID_INSTITUTION_NAME("Name: %s, is not valid"),
    USERNAME_ALREADY_EXIST("Username: %s, already exist"),
    NIF_ALREADY_EXIST("Institution with NIF: %s, already exist"),
    INVALID_EMAIL("The mail %s is invalid."),
    INVALID_NIF("The NIF %s is invalid."),
    INVALID_PASSWORD("The password %s is invalid."),
    INVALID_ROLE("The Role %s is invalid."),
    INVALID_STATE("The State %s is invalid"),
    AUTHUSER_NOT_FOUND("AuthUser not found with id %d"),
    USER_NOT_FOUND("User not found with username %s"),
    INSTITUTION_NOT_FOUND("Institution not found with id %d"),
    USER_NOT_APPROVED("The member of this institution is not yet approved"),
    USER_ALREADY_ACTIVE("User is already active with username %s"),
    INVALID_CONFIRMATION_TOKEN("Invalid confirmation token"),
    EXPIRED_CONFIRMATION_TOKEN("Expired confirmation token"),
    INVALID_LOGIN_CREDENTIALS("Invalid login credentials"),
    DUPLICATE_USER("Duplicate user: %s"),
    INVALID_THEME_NAME("Name: %s, is not valid"),
    THEME_NOT_FOUND("Theme not found with id %d"),
    ACCESS_DENIED("You do not have permission to view this resource"),
    THEME_ALREADY_EXISTS("This theme already exists"),
    THEME_CAN_NOT_BE_DELETED("Theme %s can not be deleted because has associated Institutions"),
    THEME_NOT_APPROVED("Theme %s is not yet approved"),

    // Activity
    ACTIVITY_NOT_FOUND("Activity not found with id %d"),
    ACTIVITY_NAME_INVALID("Activity Name: %s, is not valid"),
    ACTIVITY_REGION_NAME_INVALID("Region Name: %s, is not valid"),
    ACTIVITY_SHOULD_HAVE_ONE_TO_FIVE_PARTICIPANTS("Activity should have one to five participants"),
    ACTIVITY_DESCRIPTION_INVALID("Activity description is missing"),
    ACTIVITY_INVALID_DATE("Date format for %s is invalid"),
    ACTIVITY_APPLICATION_DEADLINE_AFTER_START("Activity Enrollment deadline is after start"),
    ACTIVITY_START_AFTER_END("Activity start is after end"),
    ACTIVITY_ALREADY_APPROVED("Activity is already approved with name %s"),
    ACTIVITY_ALREADY_EXISTS("Activity already exists in database"),
    ACTIVITY_ALREADY_SUSPENDED("Activity is already suspended with name %s"),
    ACTIVITY_SUSPENSION_JUSTIFICATION_INVALID("Activity suspension justification is invalid."),
    ACTIVITY_SUSPENSION_AFTER_END("Activity can't be suspended after ended."),
    ACTIVITY_ALREADY_REPORTED("Activity is already reported with name %s"),
    ENROLLMENT_NOT_FOUND("Enrollment not found with id %d"),
    ENROLLMENT_REQUIRES_MOTIVATION("To apply to an activity you have to write a motivation longer than 10 characters"),
    ENROLLMENT_VOLUNTEER_IS_ALREADY_ENROLLED("The volunteer is already enrolled"),
    ENROLLMENT_AT_LEAST_ONE_SHIFT("Enrollment must have at least one shift"),
    ENROLLMENT_AFTER_DEADLINE("The enrollment period is already closed"),
    ENROLLMENT_SHIFTS_MUST_BELONG_TO_SAME_ACTIVITY("All shifts in enrollment must belong to the same activity"),
    ENROLLMENT_SHIFTS_HAVE_OVERLAPPING_TIME("The enrolment shifts cannot have overlapping time periods"),
    PARTICIPATION_ACCEPTANCE_BEFORE_DEADLINE("The enrollment period is still open"),
    PARTICIPATION_NOT_FOUND("Participation not found with id %d"),
    PARTICIPATION_RATING_BEFORE_END("Rate only after activity end"),
    PARTICIPATION_RATING_BETWEEN_ONE_AND_FIVE("Rating %d is not in the range 1 to 5"),
    PARTICIPATION_REVIEW_LENGTH_INVALID("Invalid review with length %d"),
    PARTICIPATION_VOLUNTEER_IS_ALREADY_PARTICIPATING("The volunteer is already participating"),
    PARTICIPATION_REQUIRES_INFORMATION("Information about participation is required"),
    PARTICIPATION_MEMBER_REVIEW_NOT_ALLOWED("Members cannot create or edit a volunteer review"),
    PARTICIPATION_VOLUNTEER_REVIEW_NOT_ALLOWED("Volunteers cannot create or edit a member review"),
    PARTICIPATION_INVALID_RATING("Participation cannot be created with both volunteer and member ratings"),
    PARTICIPATION_SHIFT_NOT_IN_ENROLLMENT("The participation shift must be one of the enrollment's shifts"),
    ASSESSMENT_VOLUNTEER_CAN_ASSESS_INSTITUTION_ONLY_ONCE("Volunteer has already assessed the institution"),
    ASSESSMENT_ONLY_IF_INSTITUTION_HAS_FINISHED_ACTIVITIES("Institution does not have any finished activity"),
    ASSESSMENT_REQUIRES_REVIEW("To do an assessment have to write a review message"),
    ASSESSMENT_REVIEW_TOO_SHORT("To do an assessment have to write a review message longer than 10 characters"),
    ASSESSMENT_NOT_FOUND("Assessment not found with id %d"),
    REPORT_REQUIRES_JUSTIFICATION("To do a report have to write a justification shorter than 256 characters"),
    REPORT_ACTIVTIY_IS_ALREADY_REPORTED("The activity is already reported"),
    REPORT_AFTER_ACTIVTY_CLOSED("The activity period is already closed"),
    REPORT_NOT_FOUND("Report not found with id %d"),

    // Shift
    SHIFT_INFORMATION_REQUIRED("Shift information is required"),
    SHIFT_START_TIME_REQUIRED("Shift start time is required"),
    SHIFT_END_TIME_REQUIRED("Shift end time is required"),
    SHIFT_PARTICIPANTS_LIMIT_REQUIRED("Shift participants limit is required"),
    SHIFT_PARTICIPANTS_LIMIT_POSITIVE("Shift participants limit must be greater than zero"),
    SHIFT_LOCATION_REQUIRED("Shift location is required"),
    SHIFT_LOCATION_INVALID("Shift location must be between 20 and 200 characters"),
    SHIFT_START_TIME_BEFORE_END_TIME("Shift start time must be before end time"),
    SHIFT_START_TIME_AFTER_NOW("Shift start time must be in the future"),
    SHIFT_DATES_WITHIN_ACTIVITY("Shift dates must be within activity date range"),
    SHIFT_CURRENT_PARTICIPANTS_EXCEEDS_LIMIT("Current participants cannot exceed participants limit"),
    SHIFT_ON_NON_APPROVED_ACTIVITY("Shift cannot be associated with a non-approved activity"),
    SHIFT_NOT_FOUND("Shift not found with id %d"),
    TOTAL_PARTICIPANTS_EXCEEDS_ACTIVITY_LIMIT("Total participants of shifts exceeds activity limit"),
    ;

    public final String label;

    ErrorMessage(String label) {
        this.label = label;
    }
}